#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication postProcess -func "randomise(field=Ys.Calcite, magPerturbation=0.04)"

mv 0/'randomise(Ys.Calcite)'   0/Ys.Calcite

runApplication $application



#------------------------------------------------------------------------------
