#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# cleaning solvers

wclean all solvers
wclean all libraries
wclean all utilities

# purge option to clean executables
if [ "$1" = "--purge" ]
then
    # clean solver executables
    rm -f $FOAM_USER_APPBIN/darcyFoam
    rm -f $FOAM_USER_APPBIN/dbsFoam
    rm -f $FOAM_USER_APPBIN/dbsSimpleFoam
    rm -f $FOAM_USER_APPBIN/impesFoam
    # clean dynamic libraries
    rm -f $FOAM_USER_LIBBIN/libporousBoundaryConditions.so
    rm -f $FOAM_USER_LIBBIN/libporousModels.so
    rm -f $FOAM_USER_LIBBIN/libtoolsGIS.so
    rm -f $FOAM_USER_LIBBIN/liboherModelsGIS.so
fi
