#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling libraries
#wmake libraries/numericalMethods
wmake libraries/porousModels
wmake libraries/otherModels
wmake libraries/toolsGIS
wmake libraries/porousBoundaryConditions
##wmake libraries/geochemicalModels


# Compiling solvers
wmake solvers/darcyFoam
wmake solvers/impesFoam
wmake solvers/dbsSimpleFoam
wmake solvers/dbsFoam
wmake solvers/constantVelocityFoam
#wmake solvers/anisoImpesFoam
#wmake solvers/threePhaseImpesFoam


# Compiling utilities
#wmake utilities/setBoundaryHeadPressure
#wmake utilities/setFieldsFromXY
#wmake utilities/setFieldsFromMNT
