#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Compiling libraries
#wmake libraries/numericalMethods

##wmake libso libraries/porousInterfaceProperties/
##wmake libso libraries/porousImmiscibleIncompressibleTwoPhaseMixture/
wmake libraries/porousModels
wmake libraries/otherModels
##wmake libraries/toolsGIS
wmake libraries/porousBoundaryConditions
##wmake libraries/geochemicalModels


# Compiling solvers
wmake solvers/darcyFoam
wmake solvers/impesFoam
#wmake solvers/dbsSimpleFoam
#wmake solvers/dbsFoam
wmake solvers/constantVelocityFoam
#wmake solvers/anisoImpesFoam
#wmake solvers/threePhaseImpesFoam
##wmake solvers/hybridPorousInterFoam

# Compiling utilities
#wmake utilities/setBoundaryHeadPressure
#wmake utilities/setFieldsFromXY
#wmake utilities/setFieldsFromMNT

mkdir -p $FOAM_USER_LIBBIN
cp -a ThirdParty/phreeqcrm/lib/libphreeqcrm-3.6.2.so $FOAM_USER_LIBBIN
