#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh

runApplication $application

runApplication postProcess -time 1200,2400,3600 -func graphCell

runApplication gnuplot plot.gp

runApplication evince *.eps



#------------------------------------------------------------------------------
